DROP TABLE IF EXISTS SAMPLE;
DROP TABLE IF EXISTS USER_INFO;

--사용자 정보
CREATE TABLE USER_INFO (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(30),
    USER_NICKNAME VARCHAR(30),
    USER_PASSWORD VARCHAR(200) NOT NULL,
    USER_ROLE VARCHAR(20) NOT NULL,
    REG_ID INT,
    REG_DT DATE,
    UPD_ID INT,
    UPD_DT DATE
);

--사용자 로그인 토큰 정보
CREATE TABLE USER_INFO_TOKEN (
    USER_ID INT NOT NULL PRIMARY KEY,
    USER_ACCESS_TOKEN VARCHAR(200) NOT NULL,
    USER_REFRESH_TOKEN VARCHAR(200) NOT NULL,
    REG_ID INT,
    REG_DT DATE,
    UPD_ID INT,
    UPD_DT DATE
);

--샘플 테이블
CREATE TABLE SAMPLE
(
    SAMPLE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,   --ID
    SAMPLE_GROUP VARCHAR(10),    --그룹
    SAMPLE_NAME VARCHAR(10),     --명
    REG_ID VARCHAR(100),
    REG_DT DATE,
    UPD_ID VARCHAR(100),
    UPD_DT DATE
);
