server:
  # 내장 톰캣 포트번호
  port: 8090

spring:
  application:
    name: admin

  thymeleaf:
    cache: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    com.framework: debug
    org.springframework.web: info
    root: info
