server:
  # 내장 톰캣 포트번호
  port: 8090

spring:
  application:
    name: admin

  thymeleaf:
    cache: false

logging:
  level:
    com.framework: debug
    org.springframework.web: info
    root: info
