INSERT INTO ADMIN_INFO (
    ADMIN_ID, ADMIN_NAME, ADMIN_PASSWORD, ADMIN_LEVEL, USE_YN,
    REG_NO, REG_DT, UPD_NO, UPD_DT
) VALUES (
    'admin', '통합관리자', '1234', '1', 'Y',
    1, NOW(), 1, NOW()
);

INSERT INTO ADMIN_INFO (
    ADMIN_ID, ADMIN_NAME, ADMIN_PASSWORD, ADMIN_LEVEL, USE_YN,
    REG_NO, REG_DT, UPD_NO, UPD_DT
) VALUES (
    'admin1', '관리자1', '1234', '1', 'Y',
    2, NOW(), 2, NOW()
);

INSERT INTO USER_INFO (
    USER_EMAIL, USER_NAME, USER_NICKNAME, USER_PASSWORD, USER_ROLE,
    REG_ID, REG_DT, UPD_ID, UPD_DT
) VALUES (
    'oo2706@naver.conm', '최길동', '배부른작가', '1234', 'ROLE_USER',
    9999, NOW(), 9999, NOW()
);
