logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
  
jwt:
  #토큰 암호화 키
  secret-key: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
  #로그인 후 토큰인증이 필요없는 url
  excluding-check:
    equals-url: /login
    start-with-url: /v1/api/join/,/swagger-ui/,/v3/api-docs,/error/

auth:
  excluding-check:
    pattern: /login,/v1/view/join/**,/v1/api/join/**,/,/error/**,/swagger-ui/**,/swagger-ui/**,/favicon.ico,/v3/api-docs/**