logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error

jwt:
  #토큰 암호화 키
  secret-key: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
  #로그인 후 토큰인증이 필요없는 url
  excluding-check:
    equals-url: /login,/refresh-token
    start-with-url: /join,/swagger-ui,/v3/api-docs,/error/
  expiration:
    access-token:
      # access-token 만료시간 설정 (10분 = 1000(1초) * 60(초) * 10(분) = 600000)
      time: 600000
    refresh-token:
      # refresh-token 만료시간 설정 (10일 = 1000(1초) * 60(초) * 60(분) * 24(시간) * 10(일) = 864000000)
      time: 864000000

auth:
  excluding-check:
    pattern: /login,/join,/v1/api/join/**,/,/error/**,/swagger-ui/**,/favicon.ico,/v3/api-docs/**,/refresh-token